### ISSUE TITLE
--azure-key-vault-tenant (-kvt) isn't required 

### ISSUE THREAD

**Issue by wizedkyle** [vcsjones/AzureSignTool#109]
If you add -kvt or --azure-key-vault-tenant nothing will happen when you try to sign the file, if you remove the tenant argument it signs fine.

Only way I found this is because the azuresigntool sign --help doesn't list an option for key vault tenant so I would assume the README.md doco is out of date.

**Comment by clairernovotny** [comment]
The readme is for the code in main. @vcsjones any ETA on when you can get an updated version of the tool published?

**Comment by wizedkyle** [comment]
@clairernovotny Okay that makes sense, is it possible to add current documentation to the [NuGet package](https://www.nuget.org/packages/AzureSignTool/) as without the documentation there you naturally revert to the GitHub repo but that may not be in sync with the version in NuGet?

**Comment by vcsjones** [comment]
Documentation for the current version is available here, for what it's worth. https://github.com/vcsjones/AzureSignTool/blob/v2.0.17/README.md
