### ISSUE TITLE
error 80190194 

### ISSUE THREAD

**Issue by davej** [vcsjones/AzureSignTool#116]
Everything was working fine until about 6 hours ago and now signing is failing with `error 80190194`. I have not changed anything in my code or on Azure. I have tried with multiple different certs, both standard certs and EV certs. Same error keeps happening.

I'm trying to identify if this is an issue on Azure but the error message is not very helpful. Is there a way to get more info about the error?

The logs look like this:

```
    // everything looks good before this
    trce: AzureSignTool.Program[0]
          => File: C:/{snip}.exe
          Acquired access token from client id
    fail: AzureSignTool.Program[0]
          => File: C:/{snip}.exe
          Signing failed with error 80190194 for file C:/{snip}.exe.
    info: AzureSignTool.Program[0]
          => File: C:/{snip}.exe
          Stopping file signing.
    info: AzureSignTool.Program[0]
          Successful operations: 0
    info: AzureSignTool.Program[0]
          Failed operations: 1
```

**Comment by vcsjones** [comment]
0x80190000 is the facility for HTTP, 0x194 is 404. OR combined, that's your error number.

So somewhere during your code signing process, an HTTP 404 is happening. I would start with timestamping. Does the errror go away if you disable timestamping or switch to a different one?

As for why it "was" working, that's hard to say. Did you accidentally change the timestamping URL? Also, almost all free timestamping servers impose some kind of rate limit. Perhaps you hit their rate limit and they are giving back a not-quite helpful HTTP status code.

**Comment by davej** [comment]
@vcsjones Thank you 🙏.

It was a timestamp server 404ing as you suggested. GlobalSign seemed to have retired their timestamp server, although I can't find any info/warnings/deprecations about it. Switched to their new timestamp server (`http://rfc3161timestamp.globalsign.com/advanced`) and all seems to be good now.
