### ISSUE TITLE
intermitent (retry required) HRESULT 0x80190194 when signing

### ISSUE THREAD

**Issue by tbolon** [vcsjones/AzureSignTool#117]
For some weeks now, when I build my project, the first build fail with the following trace:

```
trce: AzureSignTool.Program[0]
      Retrieving certificate CodeSignGlobalSign.
trce: AzureSignTool.Program[0]
      Acquiring access token from client id
trce: AzureSignTool.Program[0]
      Acquired access token from client id
trce: AzureSignTool.Program[0]
      Retrieved certificate CodeSignGlobalSign.
trce: AzureSignTool.Program[0]
      Creating context
info: AzureSignTool.Program[0]
      => File: C:\agent_local\_work\28\a\Program.exe
      Signing file C:\agent_local\_work\28\a\Program.exe
trce: AzureSignTool.Program[0]
      => File: C:\agent_local\_work\28\a\Program.exe
      Getting SIP Data
trce: AzureSignTool.Program[0]
      => File: C:\agent_local\_work\28\a\Program.exe
      Calling SignerSignEx3
trce: AzureSignTool.Program[0]
      => File: C:\agent_local\_work\28\a\Program.exe
      Acquiring access token from client id
trce: AzureSignTool.Program[0]
      => File: C:\agent_local\_work\28\a\Program.exe
      Acquired access token from client id
fail: AzureSignTool.Program[0]
      => File: C:\agent_local\_work\28\a\Program.exe
      Signing failed with error 80190194 for file C:\agent_local\_work\28\a\Program.exe.
```

I have to run the build a second time for the signing to succeed.
I can confirm that the file is present on the disk.

While I am trying to diagnose what is occuring, do you have any idea what this HRESULT could mean?

Regards,

**Comment by vcsjones** [comment]
This looks similar to #116. It looks like there are problems communicating with the time stamping server.

Can you the solution a user found in https://github.com/vcsjones/AzureSignTool/issues/116#issuecomment-767605800, or an alternative timestamping server entirely?

**Comment by tbolon** [comment]
Oh, you are right, I should have tried another timestamp server. Thank you for the hint, I will try this immediately.

**Comment by tbolon** [comment]
FYI i was using http://timestamp.globalsign.com/scripts/timestamp.dll. I will switch to http://timestamp.digicert.com and report results here. Perhaps a FAQ should be added with common HRESULT errors ?

**Comment by tbolon** [comment]
Ok, it worked. Thanks!

Where did you found that 0x80190000 was for HTTP factory and the 2 last bytes were for the HTTP result code? I hoped I could find this by myself...

**Comment by vcsjones** [comment]
> Where did you found that 0x80190000 was for HTTP factory and the 2 last bytes were for the HTTP result code?

Just need to dissect the HRESULT a bit. Starting from the [HRESULT] docs.

1. `8` because it's a Microsoft owned failure code.
2. `19` in hex is 25 in base 10. If we consult that documentation page, the facility is `FACILITY_HTTP`.
3. The last two bytes are the code, which is facility-specific.
4. For `FACILITY_HTTP`, the code is going to be the HTTP status code. I don't know exactly where this is documented, it's just been some knowledge I took for granted for a very long time.

[HRESULT]: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/0642cb2f-2075-4469-918c-4441e69c548a

**Comment by vcsjones** [comment]
> Perhaps a FAQ should be added with common HRESULT errors ?

Ideally yeah, I would like to make this better. I have #61 to try and get the error output better, but yeah a FAQ would be something I can do, too.

**Comment by tbolon** [comment]
Maybe just a link to the HRESULT doc as a starting point. I could not believe I missed that... Thank you anyway, you can close this issue. I'll try to suggest something using a PR if I can.

Thank you anyway for this wonderful tool.
