### ISSUE TITLE
Are there going to be binary updates on NuGet for more recent versions?

### ISSUE THREAD

**Issue by shermanericts** [vcsjones/AzureSignTool#118]
Hey guys!
Thank you for providing this tool. It's really useful!
I'm newer to windows, so I've been using the [NuGet package here](https://www.nuget.org/packages/AzureSignTool/)

It looks built in 2018 with an older SDK package.
I see the build file for VisualStudio.  Is the recommended way going forward to just build using VisualStudio?

Apologies if this is basic knowledge or written down already somewhere.

Thanks!

**Comment by shermanericts** [comment]
ah, I think I see this one https://www.nuget.org/packages/AzureSignTool2021/0.0.0-gce87e84a58  - I'll try that.

**Comment by vcsjones** [comment]
@shermanericts that's not my package, someone appears to have forked / copied it.

> It looks built in 2018 with an older SDK package.

Yeah, I'm sorry about that. I have it on my radar to soon get a new version published that supports newer versions of .NET Core.

**Comment by shermanericts** [comment]
no worries Kevin.  It's much appreciated.  The 2021 version looks like it works!  I'll close the ticket.
