### ISSUE TITLE
Getting error 80091005 signing javascript files

### ISSUE THREAD

**Issue by LuisGonzalezLT** [vcsjones/AzureSignTool#124]
Getting this error "Signing failed with error 80091005 for file MyFile.js" with javascript files.
.exe, .dll and others seem to sign just fine but when I added .js files all of them errored.

**Comment by vcsjones** [comment]
JavaScript is not a target file type that is supported by Authenticode (part of Windows), so you cannot sign JavaScript files with AzureSignTool.

**Comment by clairernovotny** [comment]
That's not entirely true...  .ps1, .vbs and .js files are supported. Though I don't think anything actually validates signed javascript.

**Comment by ncook-hxgn** [comment]
> JavaScript is not a target file type that is supported by Authenticode (part of Windows), so you cannot sign JavaScript files with AzureSignTool.

So in short, AzureSignTool can't do all the things that signtool.exe can do? Just tried to sign a bunch of .js, .vbs with AzureSignTool: got the same error

**Comment by ncook-hxgn** [comment]
https://github.com/vcsjones/AzureSignTool/issues/137

**Comment by ncook-hxgn** [comment]
> That's not entirely true... .ps1, .vbs and .js files are supported. Though I don't think anything actually validates signed javascript.

Script files signed with SignTool.exe can be validated using PowerShell (5.1) `Get-AuthenticodeSignature`:
![image](https://user-images.githubusercontent.com/36889813/180224920-2dce5d51-f873-4213-8590-978dffe793f2.png)

🤷‍♂️
