### ISSUE TITLE
Sign multiple files is not working

### ISSUE THREAD

**Issue by front1989** [vcsjones/AzureSignTool#135]
For a single file it is working.
But when i am trying with that.
azuresigntool sign -du "www.xx.xx.com"  -kvu "https://xx.vault.azure.net" -kvi "x-x-x-x-xx" -kvs "xxx" -kvc "xxxcertificate" -nph -v -ifl "C:\Users\a031160\Downloads\test.txt"
It dont show any kind of log, it is impossible to know the issue.

**Comment by vcsjones** [comment]
The lack of logging and output for malformed CLI was fixed in 3.0.0. Please give that version a try and let me know if it is still not working as expected.

**Comment by PsychoNineSix** [comment]
I'm having the issue with the latest version, currently running my pipeline with a lot of requests to akv to circumvent the issue.

When signing 28 files, I get around 23 failed with 801901AD. (HTTP error 429)
I can only assume this is an issue with reaching the timestamp server too many times.

Maybe an optional delay between each file?

**Comment by PsychoNineSix** [comment]
I did a test with -mdop set to 1, this delays the requests enough to sign as many files as you want.
Testing with 2 resulted in the error again.

**Comment by thomas-rabiller** [comment]
Added PR to try and properly handle throttling in Azure Keyvault #237
