### ISSUE TITLE
Verbose isn't helpful and error codes mean nothing to me

### ISSUE THREAD

**Issue by scottsteesy** [vcsjones/AzureSignTool#136]
I am using a generated and self signed certificate in Azure Key Vault to attempt to automate signing of assemblies during an on-premise Azure DevOps (AzD) build. I found several articles that walked through doing this and followed all the steps, and have triple checked everything.
Every run of the test build I get the error result code -2147024894 when the build fails.
I have direct access to the machine with AzD which also runs the build agent, so I was able to find the path where AzureSignTool (AST) was installed, so I could try the same AST command line from a command prompt. There I saw no output. Tried it in PowerShell (PS) with same result, but in PowerShell if I show the values of $LASTEXITCODE I get the same -2147024894.
In PS I could tinker with the AST command line and rerun as much as I like.
I have tried purposely make each value wrong, one at a time, and the error code never changes until I add a -vkt parameter, even though my azure account is single tenant, then the error code returned changes to -2147024809.
Searching for the error codes find nothing, and the -v "verbose" parameters doesn't cause any output/message to occur.
Nothing else I've done seems to change anything, except when obvious things, like dropping 'sign' from the parameters, in which case the command outputs the usage/help ... implying I have a correct command line but something is failing.
Does anyone have any ideas?

**Comment by vcsjones** [comment]
👋 sorry for the very long reply time. -2147024894 is "file not found".

Since this was originally posted, I released 3.0 which I think greatly improves the error output situation when the command line isn't quite right. I realize the previous versions didn't do a good job of that and would often just silently exit.

If something still seems wrong with 3.0, let me know.
