### ISSUE TITLE
Release 2.0.17 failing without log, most recent works fine

### ISSUE THREAD

**Issue by maxschaf** [vcsjones/AzureSignTool#139]
Hi,

we use this tool to code sign files. Using the released version signing fails without any log information, but most recent version works as expected. Would you release a new version as nuget?

Example:
C:\Users\maxs\source\repos\AzureSignTool\src\AzureSignTool\bin\Release\netcoreapp3.1\AzureSignTool.exe sign -kvu https://myapp.vault.azure.net   -kvi C124528A-6313-4968-B119-00FD1D40387E -kvt DA9B3724-2584-4153-B421-01C9886B040E  -kvs CCCCCCC_pppppppppp-_W9a.XXXXX  -kvc TEST2  -tr http://timestamp.digicert.com -v  C:\myapp.exe

**Comment by theolivenbaum** [comment]
Same here

**Comment by GeorgDangl** [comment]
We're having the same issue. @maxschaf, did you find a way to work around this?

**Comment by theolivenbaum** [comment]
If it helps, I published the last version of this repo here: https://www.nuget.org/packages/AzureSign, based on this fork: https://github.com/theolivenbaum/AzureSignTool

**Comment by maxschaf** [comment]
> We're having the same issue. @maxschaf, did you find a way to work around this?

I built the project and we use the exe selfhosted. @theolivenbaum nugetpackage will do it easier ;).

**Comment by GeorgDangl** [comment]
Great, thank you guys😀

**Comment by vcsjones** [comment]
AzureSignTool 3.0.0 has been release. I think this can be closed. https://www.nuget.org/packages/AzureSignTool/3.0.0
