### ISSUE TITLE
Is it possible to sign .manifest and .vsto files?

### ISSUE THREAD

**Issue by rkieslinger** [vcsjones/AzureSignTool#147]
We consider moving our code signing certificate into a Azure Key Vault to be able to integrate it better in our CI/CD pipelines. Because we have to sign some office add-ins I wanted to ask, if this is possible? Currently we are using mage.exe to do that.

Thanks in advance!

**Comment by vcsjones** [comment]
AzureSignTool currently does not support these, I don't believe. AzureSignTool supports whatever Windows Authenticode supports, or old `signtool`. If you can sign it with signtool, you can probably sign it with AzureSignTool. Since you are using `mage.exe`, I don't think so.
