### ISSUE TITLE
Use GetProcAddress to test for platform support

### ISSUE THREAD

**Issue by vcsjones** [vcsjones/AzureSignTool#15]
Right now we just p/invoke `SignerSignEx3` blindly. It would be better to use `LoadLibrary` and `GetProcessAddress` to correctly handle unsupported platforms.

**Comment by onovotny** [comment]
Best that can be done is an error message, but I guess that's useful too.

**Comment by vcsjones** [comment]
Yeah. That's the intention. Right now it'll hard crash.

**Comment by vcsjones** [comment]
Decided this is probably not worth the effort and complexity of the code.
