### ISSUE TITLE
Add verbose command

### ISSUE THREAD

**Issue by onovotny** [vcsjones/AzureSignTool#16]
For some reason, when running on app services, the command is taking 11 seconds for exe's and 33 seconds for appx/appxbundle.

Verbose output to the console may help trace this.

**Comment by vcsjones** [comment]
@onovotny there is one. https://github.com/vcsjones/AzureSignTool/blob/d34abd00017ec38d395e216fa69656f141cfa1a9/AzureSignTool/Program.cs#L36

**Comment by vcsjones** [comment]
I'm not married to the logger being async if it being async makes it difficult to use in some places. I thought it might be useful for a file logger, but I don't think there is much benefit from using async here

**Comment by vcsjones** [comment]
Fixed by PR #17
