### ISSUE TITLE
Support for /as option

### ISSUE THREAD

**Issue by nishaatr** [vcsjones/AzureSignTool#168]
Looks like AzureSignTool does not support singtool.exe /as option (https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe). I tried to sign with sha1 then sha256 but signature is overwritten

Any workaround or possibly support /as in the future? (I need this pretty soon)

Thanks

**Comment by vcsjones** [comment]
This is unfortunately not possible with AzureSignTool, and it's mentioned at the bottom of the readme, briefly.

The underlying Windows signing API being used, `SignerSignEx3`, does not support appending signatures when used with the signer callbacks.

**Comment by nishaatr** [comment]
Thank you @vcsjones. Appreciated for the quick response

I found this explicitly mentioned in this article https://vcsjones.dev/azure-signtool/ which looks like its authored by youself
