### ISSUE TITLE
Fails to installs : Using AzureSignTool to sign files with Azure DevOps

### ISSUE THREAD

**Issue by cadology** [vcsjones/AzureSignTool#172]
I'm trying to install AzureSignTool in my pipeline in Azure DevOps. I'm using the following YAML to install

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install AzureSignTool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global azuresigntool --version 3.0.0'

I get...

_The tool package could not be restored.
Tool 'azuresigntool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool._

My code uses a package from one of my other products stored as a package in Artifacts in another DevOps project and when trying to install AzureSignTool, I see this message in the output..

C:\Users\VssAdministrator\AppData\Local\Temp\ke50zurg.yof\restore.csproj : error NU1301: Unable to load the service index for source https://fpassistant.pkgs.visualstudio.com/_packaging/FPAssistantSCL/nuget/v3/index.json.

At this stage, I'm just trying to install AzureSignTool so I can't understand why this NU1301 message is coming from!!

Any thoughts please?

Thanks

**Comment by paralexm** [comment]
How are you providing the `nuget.config` for your project restore? Do you have a nuget.org source in there?

**Comment by cadology** [comment]
> How are you providing the `nuget.config` for your project restore? Do you have a nuget.org source in there?

I'm not as I don't want my project to restore. Instead, I have added a .NET Core task to my devops pipeline with a custom Command to restore (YAML in message above). I can't use the project as the package is not compatible with my project target.

Thanks for replying...I'm going to try and give access from this DevOps project to my other so it can access the package in the Artifacts.

**Comment by cadology** [comment]
Hi, I think the source are there as I get...

Registered Sources:
  1.  FPAssistantSCL [Enabled]
      https://fpassistant.pkgs.visualstudio.com/_packaging/FPAssistantSCL/nuget/v3/index.json
  2.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json

Hmmm, not sure what to try next
