### ISSUE TITLE
Accept multiple files as input

### ISSUE THREAD

**Issue by onovotny** [vcsjones/AzureSignTool#18]
When signing a lot of files, it could be beneficial to pass them all into signtool. Perhaps as an input file with one file per line?

An option can specify the max concurrency so signing can be done in parallel.

Benefits: Getting access tokens/certificate operations would be amortized for all files in the batch instead of for each file.

**Comment by vcsjones** [comment]
Next question: does failing to sign one stop the entire operation, or try to continue for each file?

**Comment by onovotny** [comment]
I was thinking that the cmd line would be too long if there are too many files and the path is included
