### ISSUE TITLE
Sign with NET7

### ISSUE THREAD

**Issue by hrlourenco** [vcsjones/AzureSignTool#190]
Hello,

When trying to sign with an agent (azure devops) without NET6 installed, it fails requesting NET6 to be installed.
Is there some workaround to allow use the tool without NET6 in the agent?

**Install azuresigntool:**
![image](https://user-images.githubusercontent.com/6207067/210770106-089d589c-37ed-4e42-a354-97c13d66664f.png)

**Executing:**
![image](https://user-images.githubusercontent.com/6207067/210769904-b3d42a4a-5523-4eb1-ab95-c09e4e39bb42.png)

Thank you

**Comment by vcsjones** [comment]
I don't know about any particular work around for this. My preference would be to stay on an LTS version of .NET. I suppose we could bring back the roll forward, which I think is what allows AST 3.x to work on future runtimes.

**Comment by BryanEuton** [comment]
The only work around that I've seen for this is to actually install the .net6 version before this step:
` ``
    - task: UseDotNet@2
      displayName: Install .NET 6 Version for AzureSignTool
      condition: succeeded()
      inputs:
        packageType: 'sdk'
        version: '6.0.300'
        installationPath: $(Agent.TempDirectory)/dotnet
```

**Comment by ZdenekS81** [comment]
I experienced the same issue on an agent with NET8 SDK and the work around which worked for me was the roll-forward behavior set via the environment variable:
```
env:
  DOTNET_ROLL_FORWARD: Major
```

**Comment by vcsjones** [comment]
Closing this for now, as AzureSignTool is now updated for .NET 8.
