### ISSUE TITLE
Add support for signtool.exe sign /as option

### ISSUE THREAD

**Issue by old-pigeon** [vcsjones/AzureSignTool#192]
AzureSignTool should support the `signtool.exe sign /as` option which allows to append a signature instead of replacing it.

The current existing option `--additional-certificates` is not sufficient, as a file might already have a signature for which we don't own the private key.

**Comment by judge2020** [comment]
See https://github.com/vcsjones/AzureSignTool/issues/168. This seems to be a Windows API issue.
