### ISSUE TITLE
Failed with 80072EFD

### ISSUE THREAD

**Issue by MeijisIrlnd** [vcsjones/AzureSignTool#201]
Hey, I'm trying to sign an INNO Setup generated installer on Windows 10, and I used [this super helpful article](https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/) as a reference for the process. The signing process fails after calling `SignerSignEx3`, here's the relevant part of the log, all fails after this point: 
```
trce: AzureSignTool.SignCommand[0]
      => File: OurInstaller.exe
      Calling SignerSignEx3
fail: AzureSignTool.SignCommand[0]
      => File: OurInstaller.exe
      Signing failed with error 80072EFD.
 ```

the command I'm trying to sign with is: 
`azuresigntool sign --verbose -kvu "[OUR_KEYVAULT_URI"] -kvi "[OUR_CLIENT_ID]" -kvt "[OUR_TENANT_ID]" -kvs "[OUR_CLIENT_SECRET]" -kvc "[OUR_CERT_NAME]" -tr https://timestamp.digicert.com -v OurInstaller.exe`

Obviously without the square braces and with actual values for the parameters. 

I wasn't able to find any info about the error ID, unless I'm missing a list of error codes and their causes somewhere,
any advice would be super appreciated!

EDIT: It also fails with  80072EE2 sometimes as well

**Comment by MeijisIrlnd** [comment]
... using https:// instead of http:// was my issue, my bad, that was a rollercoaster

**Comment by vcsjones** [comment]
Glad you figured it out. I'll see if I can improve the error output here, or at least add a warning.
