### ISSUE TITLE
Files to sign to support wildcards

### ISSUE THREAD

**Issue by andyfisher100** [vcsjones/AzureSignTool#206]
It would be nice if the file to sign could support wildcard signing to sign multiple files from one command such as the following to sign multiple msi files in the same directory
C:\BuildOutput\\*.msi

This is something that is supported by sign tool itself and would makes life a little easier.

I do realise that the app supports the passing of a file that can contain multiple files to sign, maybe you suggestion is this instead of using wildcards?

**Comment by malikirfan** [comment]
Yes, it will surely help to support wildcard. As I need to sign all "exe" files in artifact.

**Comment by johnhydemtm365** [comment]
Any thoughts on implementing this. We have an electron build that puts the version number into the file name..... so its dynamic...
