### ISSUE TITLE
AzureSignTool on local on prem computers

### ISSUE THREAD

**Issue by jmecosta** [vcsjones/AzureSignTool#218]
Hi,

Is there any restrictions on using this tool on on prem computers? Besides making sure we have access to azure infrastructure from those on prem computers?

thanks

**Comment by GruberMarkus** [comment]
I use AzureSignTool on-prem and on cloud server since half a year, have signed several thousand files in this time and did not observe a problem in any of the environments.

**Comment by jmecosta** [comment]
thanks for confirming :)
