### ISSUE TITLE
Command line option `/as` (Append Signature) missing

### ISSUE THREAD

**Issue by michaelkauflin** [vcsjones/AzureSignTool#236]
Hi @vcsjones 

We need to switch our code signing approach from SignTool to AzureSignTool and just found out that the *Append Signature* command line option in AzureSignTool is missing. Our use case is that we need to sign all deployed binaries with our certificate, keeping the existing one.

Is there any plan to incorporate the append signature functionality to AzureSignTool as well?

Thanks a lot for any update

**Comment by vcsjones** [comment]
The appendix signature (-as) option was just added in the latest release of AST. Can you give it a try and let me know how it works for you?

**Comment by michaelkauflin** [comment]
> The append signature (-as) option was just added in the latest release of AST. Can you give it a try and let me know how it works for you?

Hi Kevin

We will check it out and get back to you - thanks a lot for your support!

Cheers
Michael

**Comment by michaelkauflin** [comment]
> The append signature (-as) option was just added in the latest release of AST. Can you give it a try and let me know how it works for you?

@vcsjones : works like a charm 🚀  - I will close the issue 👍

**Comment by michaelkauflin** [comment]
feature available with last release
