### ISSUE TITLE
Sign folder contents and passing in filter

### ISSUE THREAD

**Issue by igormesaros84** [vcsjones/AzureSignTool#267]
In my scenario I would like to sign most of the files in a folder, because:
a) I have a lot of files and would like to avoid having to specify each file when signing
b) I would have to update this every time theres a new file added.

What I would like to have is the ability to sign all files in a folder matching a string that all files contain, or alternatively passing in a list of files that I want excluded from signing.

I see I can use `--input-file-list` but I wonder if passing in a folder would be something worthwhile adding?

**Comment by vcsjones** [comment]
This will be in AzureSignTool v6.0, of which a beta was just published. You can do something like `azuresigntool ... C:\files\*.exe` to sign all EXEs in a folder, for example.
