### ISSUE TITLE
AzureSignTool Fails to Sign Native WiX C# Custom Action DLL

### ISSUE THREAD

**Issue by iamcloud-curt** [vcsjones/AzureSignTool#273]
We're encountering an error when using AzureSignTool to sign a native DLL built as a C# Custom Action for WiX v3. The signing process fails with the following error code:

Signing C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll
trce: AzureSignTool.SignCommand[0]
      Retrieving certificate GSCodeSigningEVCert.
trce: AzureSignTool.SignCommand[0]
      Retrieved certificate GSCodeSigningEVCert.
trce: AzureSignTool.SignCommand[0]
      Creating context
info: AzureSignTool.SignCommand[0]
      => File: C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll
      Signing file.
trce: AzureSignTool.SignCommand[0]
      => File: C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll
      Getting SIP Data
trce: AzureSignTool.SignCommand[0]
      => File: C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll
      Calling SignerSignEx3
fail: AzureSignTool.SignCommand[0]
      => File: C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll
      Signing failed with error 800700C1.
info: AzureSignTool.SignCommand[0]
      => File: C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll
      Stopping file signing.
info: AzureSignTool.SignCommand[0]
      Successful operations: 0
info: AzureSignTool.SignCommand[0]
      Failed operations: 1
C:\a\_temp\e58b8ff8-22dd-4d85-b3dc-225c52086806.ps1 : Failed to sign C:\a\1\installerTools\BlockingApps\bin\Release\BlockingAppsCustomAction.CA.dll

Upon inspection, it was confirmed that this is a **native (unmanaged) DLL** created by the WiX Toolset in Visual Studio 2022. The AzureSignTool command we are using to sign this file is:

AzureSignTool sign -kvu "$(SigningVaultURL)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" -kvt "$(SigningClientTenantId)" -kvc "$(SigningCertName)" -tr "http://timestamp.digicert.com" -v $file

Despite the DLL being a valid, native WiX C# Custom Action, the signing fails specifically on this native DLL, whereas managed assemblies are successfully signed.

Could you provide any insight on whether AzureSignTool supports signing native DLLs, particularly those generated by the WiX toolset?

**Comment by vcsjones** [comment]
AzureSignTool should be able to sign a DLL regardless of it being managed or unmanaged. Many of AzureSignTool's tests are on a native library.

That said, the error from your log is 0x800700C1, which is "Not a valid Win32 application". So, Windows thinks otherwise about the validity of the library.

I don't suppose you have a sample library that reproduces the problem?

**Comment by vcsjones** [comment]
This is a bug in WiX that was previously reported here https://github.com/wixtoolset/issues/issues/6089 and fixed. If I am understanding their repository correctly, they fixed it in v3.14.1. Can you try upgrading your WiX toolset?

For what it's worth, I can reproduce this with Microsoft's signtool, so there is not much that AzureSignTool could do about it. 

<img width="1334" alt="Screenshot 2024-09-26 at 2 29 36 PM" src="https://github.com/user-attachments/assets/c5858fa3-2388-4647-9b77-200eb58ae871">

**Comment by vcsjones** [comment]
If you are still having issues signing this binary - I would suggest reaching out to WiX, since neither signtool nor AzureSignTool can sign it.

**Comment by iamcloud-curt** [comment]
Upgraded to latest WiX toolset and seems to have fixed locally in signtool.

![image](https://github.com/user-attachments/assets/2f7abf55-c587-4717-9465-495ebf4e28ee)

I have just committed the reference changes to the solution and running my pipeline now to test :)

Great catch mate if this fixes it

**Comment by iamcloud-curt** [comment]
![image](https://github.com/user-attachments/assets/cc12d479-deff-4345-aa1b-786af93fa793)
signtool.exe works for that CA.dll file but re-running pipeline I got the same error

info: AzureSignTool.SignCommand[0]
      Failed operations: 1
WARNING: Failed to sign C:\a\2\installerTools\FatalErrorLog\bin\Release\FatalErrorLog.CA.dll with error code -1610612734. Skipping.
Signing C:\a\2\installerTools\FatalErrorLog\bin\Release\FatalErrorLog.dll
[FatalErrorLog.zip](https://github.com/user-attachments/files/17155399/FatalErrorLog.zip)

Uploaded latest FatalErrorLog.zip CA files can you try AzureSignTool your end?

**Comment by vcsjones** [comment]
> an you try AzureSignTool your end?

I tried the latest one you uploaded and it worked for me. I noticed that the paths are different from your original report, any chance you have multiple copies of this library that need to be updated, or perhaps the pipeline did not pick up the change, or also needs a WiX update?

**Comment by iamcloud-curt** [comment]
Fixed in Azure pipeline now with this step and my DLLs are now getting signed

- pwsh: |
    Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314.exe' -OutFile 'wix314.exe'
    Start-Process -FilePath ./wix314.exe -ArgumentList '/install', '/quiet', '/norestart' -NoNewWindow -Wait
    $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.14\SDK"
    $command = Get-Command 'C:\Program Files (x86)\WiX Toolset v3.14\SDK\MakeSfxCA.exe'
    Write-Host "WiX version in use: $($command.Path)"
  displayName: 'Install WiX Toolset 3.14'
