### ISSUE TITLE
SHA1 signing

### ISSUE THREAD

**Issue by jariq** [vcsjones/AzureSignTool#28]
Hello Kevin,

thanks for creating this tool. It helped me to start using Key Vault quickly and was much easier to understand (at least for me) than the official samples. I've noticed the current [README][0] states that:

> SHA1 signing is not supported by Azure Key Vault.

I just wanted to let you know it is possible to create SHA1 signature with `RSNULL`  algorithm as I've demonstrated on [StackOverflow][1] few minutes ago.

Keep up the great work!

[0]: https://github.com/vcsjones/AzureSignTool#current-limitations
[1]: https://stackoverflow.com/a/49082869/3325704

**Comment by onovotny** [comment]
Thanks @jariq! I guess we could impl Sha1 for completeness, though I can't think of any good reason to enable people to create signatures using it.

**Comment by jariq** [comment]
Many binaries in my system are signed with just SHA-1:

![image](https://user-images.githubusercontent.com/1163818/36934676-a9f94ce2-1eed-11e8-9551-6386f16ee19c.png)

Some of them with both SHA-1 and SHA-256:

![image](https://user-images.githubusercontent.com/1163818/36934736-28e373c0-1eee-11e8-9af3-b0d6dc05ea1d.png)

And others with just SHA-256:

![image](https://user-images.githubusercontent.com/1163818/36934770-8f94b552-1eee-11e8-877d-3b3f753eabf2.png)

I'm not sure why they are using SHA-1. Maybe there is some extra old system such as XP SP2 they need to support?

**Comment by vcsjones** [comment]
Thanks for sharing, I'm going to look in to this and implement it.

**Comment by vcsjones** [comment]
This is something that https://github.com/onovotny/RSAKeyVaultProvider needs to implement now since this tool has deferred all responsibility to there. There is an open PR for it, so closing this issue here.

**Comment by onovotny** [comment]
Should the fd parameter support it?

**Comment by vcsjones** [comment]
@onovotny I believe it already does (it shares the same parsing that was used for timestamp algorithm).

https://github.com/vcsjones/AzureSignTool/blob/97ba9cbf35f90d4dd92d3aef2f6a2df263a3df76/src/AzureSignTool/Program.cs#L313L314

**Comment by vcsjones** [comment]
We should update the documentation if RSAKeyVault accepts the SHA1 change, though.

**Comment by onovotny** [comment]
yeah, and we'll need to update the dependency to take the newer version

**Comment by vcsjones** [comment]
OK, you're right. I'll leave open for now.

**Comment by onovotny** [comment]
Package is published now:
https://www.nuget.org/packages/RSAKeyVaultProvider/1.1.22
