### ISSUE TITLE
MSIX Support

### ISSUE THREAD

**Issue by vcsjones** [vcsjones/AzureSignTool#29]
Figure out how to get this working with MSIX and/or what the requirements are.

**Comment by onovotny** [comment]
It's likely just the same as appx -- will be a SIP for Authenticode + a util/API for extracting the files and editing the manifest to ensure the publisher matches the cert.

**Comment by vcsjones** [comment]
That seems to be my understanding. At a minimum extensions will have to be added here. https://github.com/vcsjones/AzureSignTool/blob/3362e5d231745b2793c0b80f96f5c1fc6de5043e/AzureSignTool/SipExtensionFactory.cs#L28

**Comment by vcsjones** [comment]
@onovotny have you been able to find a list of msix extensions?

**Comment by onovotny** [comment]
Done in https://github.com/vcsjones/AzureSignTool/pull/52. More work elsewhere to make it work on downlevel OS's.
