### ISSUE TITLE
Default platform for tool?

### ISSUE THREAD

**Issue by onovotny** [vcsjones/AzureSignTool#3]
What should the default platform be for the tool, x86 or x64? I believe the way it's compiled now, it's x86. Either way is okay by me but I think it should be explicitly documented somewhere. Reason is if native dll's are required for #2, then we need to be aware of the platform.

**Comment by vcsjones** [comment]
I believe it's compiled as Any CPU. If we have to pick one, I'd sooner pick x64 over x86.

**Comment by onovotny** [comment]
When I look at VS and the properties page, the PlatformTarget appears to default to x86. It may need an explicit `PlatformTarget` property in the csproj.

**Comment by vcsjones** [comment]
Fixed in #4.
