### ISSUE TITLE
Friendly error message for mismatched Publisher on Appx

### ISSUE THREAD

**Issue by onovotny** [vcsjones/AzureSignTool#5]
The SignerSignEx3 api will return an error code if the publisher identity in the `AppxManifest.xml` doesn't match the subject of the certificate. As this may be a common error, would be worth trapping and returning a better error message.

**Comment by vcsjones** [comment]
It actually seems to return `8007000B` which is the exact same HRESULT as BadImageFormatException, or when you mix x86 and x64. (Hilarious). I think it's worth treating it as "mismatched certs", though.

Ideas on what the error message should be?

**Comment by onovotny** [comment]
"The Publisher Identity in the AppxManifest.xml does not match the subject on the certificate." ?

**Comment by onovotny** [comment]
maybe display the subject, value should be: "CN=Foo, O=Bar, ..."?

**Comment by ccpp** [comment]
Hi all, I find this error message misleading. I get `COR_E_BADIMAGEFORMAT` for a completely different reason. My subjects do match, but whenever I sign a .msix and specify a `--file-digest` other than SHA256 I get this highly misleading error message.
