### ISSUE TITLE
Allow page signing

### ISSUE THREAD

**Issue by vcsjones** [vcsjones/AzureSignTool#8]
SignTool allows opting in to page signing. We should allow it as well.

**Comment by onovotny** [comment]
What does this option do?

Unrelated thought, but does the cmd parser support the `/` delimiter? That would make it a drop-in replacement for signtool for many cases

**Comment by vcsjones** [comment]
>What does this option do?

It's on by default for Windows 7+, I think. Might be Windows 8. But there are options to explicitly opt in or out of it during signing.

It means that the OS verifies the PE as it is loaded in to memory, so you can be sure the PE in memory is correct as well.

> Unrelated thought, but does the cmd parser support the / delimiter? That would make it a drop-in replacement for signtool for many cases

I'm not sure. If it doesn't I think it's a worthwhile goal. I've tried to keep the names the same.
