### ISSUE TITLE
Need to doc Managed Identity usage

### ISSUE THREAD

**Issue by clairernovotny** [vcsjones/AzureSignTool#87]
Now that Managed Identities are supported, the readme needs updates with the new parameters.

**Comment by blowdart** [comment]
It does? Does that mean Azure Pipelines will work with configured creds? That would be happiness.

**Comment by clairernovotny** [comment]
It got added as part of my update to `RSAKeyVaultProvider`. It's the `-kvm` / `--use-managed-identity` option. 
https://github.com/vcsjones/AzureSignTool/blob/master/src/AzureSignTool/SignCommand.cs#L42

Not sure if Pipelines supports MSI's though.

**Comment by blowdart** [comment]
https://stefanstranger.github.io/2019/03/02/ManageIdentityInServiceConnections/ appears to give me hope.

**Comment by clairernovotny** [comment]
Yeah, just saw that it's with a private vm.

**Comment by blowdart** [comment]
https://azuredevopslabs.com/labs/vstsextend/azurekeyvault/ talks about secrets only so there's something there

**Comment by clairernovotny** [comment]
That's using a Key Vault task with an ARM service connection. I have no idea how to use a service connection outside of a task to get a credential....that's really what's needed here.

**Comment by blowdart** [comment]
OK, let's ask around internally :) Maybe there's something in the custom task we can leverage

**Comment by vcsjones** [comment]
This was fixed in #98
